### ISSUE TITLE
Working???

### ISSUE THREAD

**Issue by LeeUnd** [markhillard/Editor#14]
**Describe the bug**
Not really a 'bug' but I can't get it to work. (I am using it locally.) In the left panel, 'HTML' is highlighted. I type in text and nothing appears in the right panel. I try to switch to CSS or JS and it stays on 'HTML'. The 'tools' doesn't drop down.

What am I doing wrong?

**Comment by markhillard** [comment]
@LeeUnd are you seeing any errors in your dev tools console? Either on page load or when clicking on something?

Also, which web browser are you using? I'd like to test it in the same browser myself and see if there is an issue/bug.

**Comment by naiveallen** [comment]
> @LeeUnd are you seeing any errors in your dev tools console? Either on page load or when clicking on something?
> 
> Also, which web browser are you using? I'd like to test it in the same browser myself and see if there is an issue/bug.

I have a same issue. Actually, it worked well yesterday... But today it happens !  
Here is the console error log: 
![Snipaste_2019-06-17_10-44-10](https://user-images.githubusercontent.com/34903600/59624913-de6edd80-90ec-11e9-8094-919ceaaefed1.png)
Hope it useful for you. Thank you

**Comment by markhillard** [comment]
@LeeUnd and @naiveallen, this is happening because of a 3rd party plugin called -prefix-free - see https://leaverou.github.io/prefixfree/#faq - If you're using Chrome, you'll need to enable local XHR by enabling the `--allow-file-access-from-files` flag.

See https://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode for instructions.

Once you do this you should no longer get those errors and the application should work properly in your local environment.
