### ISSUE TITLE
HTML code preview is not showed correctly

### ISSUE THREAD

**Issue by naiveallen** [markhillard/Editor#15]
When I input '<h1>Hello</h1>' in html code pane without css code, in the preview pane, it just shows Hello, but not h1 font.

**Comment by markhillard** [comment]
Yup, it should do that because there is no CSS. Since [Eric Meyer's CSS reset](https://meyerweb.com/eric/tools/css/reset/) is loaded automatically, it will "normalize" all default browser styles.

It's up to you to define your own typography styles. If you need some quick CSS code to copy/paste, try using https://type-scale.com/. It will generate a heading stack for you.
